
-- SUPPRESSION DES TABLES SI ELLES EXISTENT
DROP TABLE IF EXISTS ETUDIANT_COURS;
DROP TABLE IF EXISTS COURS;
DROP TABLE IF EXISTS ETUDIANT;
DROP TABLE IF EXISTS PROFESSEUR;

-- CREATION DE LA TABLE PROFESSEUR
CREATE TABLE PROFESSEUR
(
CODE_PROF INT PRIMARY KEY,
NOM_PROF VARCHAR (50),
PRENOM_PROF VARCHAR (50)
);

-- CREATION DE LA TABLE ETUDIANT

CREATE TABLE ETUDIANT
(
N_ETUD INT PRIMARY KEY,
NOM_ETUD VARCHAR (50),
PRENOM_ETUD VARCHAR (50),
DATE_INSCRIP DATE,
EMAIL VARCHAR (100)
);

-- CREATION DE LA TABLE COURS

CREATE TABLE COURS
(
CODE_COURS INT PRIMARY KEY,
NOM_COURS VARCHAR (100),
CODE_PROF INT,
FOREIGN KEY (CODE_PROF) REFERENCES PROFESSEUR(CODE_PROF)
);

-- CREATION DE LA TABLE ETUDIANT_COURS AVEC la CLE COMPOSITE

CREATE TABLE ETUDIANT_COURS
(
N_ETUD INT,
CODE_COURS INT,
DATE_INSCRIP DATE,
MNT_PAYE DECIMAL (6,2),
GRADE VARCHAR (2),
PRIMARY KEY (N_ETUD, CODE_COURS),
FOREIGN KEY (N_ETUD) REFERENCES ETUDIANT (N_ETUD),
FOREIGN KEY (CODE_COURS) REFERENCES COURS (CODE_COURS)
);

-- INSERTION DE PROFESSEURS
INSERT INTO PROFESSEUR (CODE_PROF, NOM_PROF, PRENOM_PROF) VALUES
(1, 'SOMDA', 'Flavien'),
(2, 'SANA', 'Mohamadi'),
(3, 'KABORE', 'Kizito');

-- INSERTION DE COURS
INSERT INTO COURS (CODE_COURS, NOM_COURS, CODE_PROF) VALUES
(101, 'Virtualisation', 1),
(102, 'Securite informatique', 2),
(103, 'Base de données avancées', 3);

-- Insertion d'étudiants
INSERT INTO ETUDIANT (N_ETUD, NOM_ETUD, PRENOM_ETUD, DATE_INSCRIP, EMAIL) VALUES
(1, 'Zoundi', 'philippe', '2024-09-01', 'philippe.zoundi@example.com'),
(2, 'moreno', 'codja', '2024-09-02', 'codja.moreno@example.com'),
(3, 'bendja', 'Sophie', '2024-09-02', 'sophie.bendja@example.com'),
(4, 'Ouedraogo', 'rapouyouga', '2024-09-02', 'rapougouya.ouedraogo@example.com');

-- Inscriptions des étudiants aux cours
INSERT INTO ETUDIANT_COURS (N_ETUD, CODE_COURS, DATE_INSCRIP, MNT_PAYE, GRADE) VALUES
(1, 101, '2024-09-05', 250.00, 'A'),
(2, 102, '2024-09-06', 200.00, 'B');

